# coding: utf-8
get_ipython().run_line_magic('cls', '')
get_ipython().run_line_magic('history', '')
get_ipython().run_line_magic('history', '-c')
get_ipython().run_line_magic('history', '-d')
get_ipython().run_line_magic('run', 'basic.py')
get_ipython().run_line_magic('run', 'test.py')
get_ipython().run_line_magic('cls', '')
def showlog(a):
    print("Logging");
    
get_ipython().run_cell_magic('save', '', '\n')
get_ipython().run_line_magic('save', '`runtest.py`')
get_ipython().run_line_magic('run', 'runtest/py')
get_ipython().run_line_magic('run', 'runtest.py')
get_ipython().run_line_magic('cls', '')
get_ipython().run_line_magic('run', 'showLog.py')
get_ipython().run_line_magic('timeit', '')
get_ipython().run_line_magic('timeit', '')
get_ipython().run_cell_magic('timeit', '', 'L []\nfor n in range(100):\n    L.append(n**2)\n    \n')
get_ipython().run_cell_magic('timeit', '', 'L = []\nfor n in range(100):\n    L.append(n**2)\n')
get_ipython().run_cell_magic('save', 'magic_cmd.py', '\n')
get_ipython().run_line_magic('cls', '')
get_ipython().run_cell_magic('timeit', '', 'L = []\nfor n in range(100):\n    L.append(n**2)\n    \n')
get_ipython().run_cell_magic('timeit', '?', '\n')
get_ipython().run_line_magic('pinfo', '%%timeit')
get_ipython().run_line_magic('ls', '')
get_ipython().run_line_magic('cls', '')
get_ipython().run_line_magic('magic', '')
get_ipython().run_line_magic('magic', '%save')
get_ipython().run_line_magic('cls', '')
get_ipython().run_line_magic('pinfo', '%timeit')
get_ipython().run_line_magic('magic', '')
get_ipython().run_line_magic('cls', '')
get_ipython().run_line_magic('Ismagic', '%save')
get_ipython().run_line_magic('lsmagic', '%save')
